---
#safelist
branches:
  only:
  - dev
  - master


sudo: required
services:
  - docker

before_install:
  - docker --version
  - docker info
  - docker ps -a

script: docker build ./

after_script:
  - docker images
  - docker ps -a