---
#safelist
branches:
  only:
  - master


sudo: required
services:
  - docker

before_install:
  - docker login -u toddd79 --password-stdin $(echo $docker_pass)
  - docker --version
  - docker info
  - docker build ./
  - docker rmi $(docker images -q)
  - docker ps -a
  - docker images

script: docker build -t minecraft_server

after_script:
  - docker push toddd79/minecraft_server
  - docker rmi $(docker images -q)
  - docker ps -a
  - docker images
