---
#safelist
branches:
  only:
  - master


sudo: required
services:
  - docker

before_install:
  - docker login -u $docker_user -p $docker_pass
  - docker --version
  - docker info
  - docker build ./
  - docker kill $(docker ps -q)
  - docker rm $(docker ps -a -q)
  - docker rmi $(docker images -q)
  - docker ps -a
  - docker images

script: docker build -t minecraft_server

after_script:
  - docker push $docker_user/minecraft_server
  - docker kill $(docker ps -q)
  - docker rm $(docker ps -a -q)
  - docker rmi $(docker images -q)
  - docker ps -a
  - docker images